### ISSUE TITLE
Tableau is not recognizing the field names

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-7#5]
When I extracted the raw data file into Tableau, Tableau did not recognize any of the field names. When I try to examine the export file in my terminal, I don't get the field names like I the assignment says I'm supposed to. Instead, I get the first row of actual data:

![image](https://cloud.githubusercontent.com/assets/8551620/4581085/e5ea2728-4fdc-11e4-8863-b3a7996fcf1a.png)

Is there something I'm missing? Should I go ahead and rename the fields in Tableau?

**Comment by BrianNewsom** [comment]
Hey Chris,

I am having the same problem. I have a messy workaround for what I can discern of the issue here.  The files are not prepended by the headers.  I found them online at: http://gdeltproject.org/data/lookups/CSV.header.dailyupdates.txt

So i copied these into a file I called headers.txt

```
GLOBALEVENTID   SQLDATE MonthYear   Year    FractionDate    Actor1Code  Actor1Name  Actor1CountryCode   Actor1KnownGroupCode    Actor1EthnicCode    Actor1Religion1Code Actor1Religion2Code Actor1Type1Code Actor1Type2Code Actor1Type3Code Actor2Code  Actor2Name  Actor2CountryCode   Actor2KnownGroupCode    Actor2EthnicCode    Actor2Religion1Code Actor2Religion2Code Actor2Type1Code Actor2Type2Code Actor2Type3Code IsRootEvent EventCode   EventBaseCode   EventRootCode   QuadClass   GoldsteinScale  NumMentions NumSources  NumArticles AvgTone Actor1Geo_Type  Actor1Geo_FullName  Actor1Geo_CountryCode   Actor1Geo_ADM1Code  Actor1Geo_Lat   Actor1Geo_Long  Actor1Geo_FeatureID Actor2Geo_Type  Actor2Geo_FullName  Actor2Geo_CountryCode   Actor2Geo_ADM1Code  Actor2Geo_Lat   Actor2Geo_Long  Actor2Geo_FeatureID ActionGeo_Type  ActionGeo_FullName  ActionGeo_CountryCode   ActionGeo_ADM1Code  ActionGeo_Lat   ActionGeo_Long  ActionGeo_FeatureID DATEADDED   SOURCEURL
```

Then used some bash magic to prepend this to the large file.

```
cat headers.txt | cat - 20141008.export.CSV > fixedFile.csv
```

Now we can head the file to see that it has the column names

```
head -n 1 fixedFile.csv
```

And the second line is the old first line.

Now when I put the data into tableau it seems to work as advertised.  Note that I haven't actually done anything in tableau I just tried out the load and it recognizes the field names.

Let me know if something breaks..

Brian

**Comment by chrisbopp** [comment]
Thanks so much for sharing your solution Brian! I forgot to include that step in the Checkpoints, that's exactly what you should do! I'll update the challenge to include that information.
